### ISSUE TITLE
您好，请问支持ipad适配吗？

### ISSUE THREAD

**Issue by 877209649** [lixiang1994/AutoInch#7]
您好，请问支持ipad适配吗？

**Comment by lixiang1994** [comment]
ipad按理说不需要，但可以重写转换计算的闭包支持




| |
LEE
邮箱：18611401994@163.com
|

Signature is customized by Netease Mail Master

在2019年08月01日 17:15，877209649 写道：

您好，请问支持ipad适配吗？

**Comment by 877209649** [comment]
好的，谢谢
