### ISSUE TITLE
有个疑问，如果设计图是iPhoneX的，如何适配非刘海屏（6，7，8等）

### ISSUE THREAD

**Issue by leasual** [lixiang1994/AutoInch#8]
40.auto() 在iPhone X和 iPhone 8 表现上数值是相等的，因为宽度都是375，但是高度是不同的，按照iPhoneX的标注，在iPhone 8上面显示不太正常。

**Comment by lixiang1994** [comment]
auto默认计算规则是基于屏幕宽度的, 你可以重写计算闭包(不建议), 也可以使用inch相关的函数解决这类问题 例如 `100.ifull(120)`

**Comment by leasual** [comment]
感谢回答
